# Symbolic Computation of Lobatto Tableaus

In [180]:
using GeometricIntegrators.CommonFunctions
using GeometricIntegrators.BasisFunctions
using GeometricIntegrators.Quadratures
using GeometricIntegrators.Utils
using LinearAlgebra
using Polynomials
using Test

## Nodes

In [4]:
function get_lobatto_nodes_legacy(s)
    if s == 1
        @error "Lobatto nodes for one stages not defined."
    elseif s == 2
        c = @dec128 [0, 1]
    elseif s == 3
        c = @dec128 [0,    1/2,    1]
    elseif s == 4
        c = @dec128 [0,    (5-√5)/10,    (5+√5)/10,    1]
    elseif s == 5
        c = @dec128 [0,    1/2-√21/14,    1/2,    1/2+√21/14,    1]
    else
        c = nodes(LobattoLegendreQuadrature(s))
    end

    return c
end

get_lobatto_nodes_legacy (generic function with 1 method)

In [82]:
function get_lobatto_nodes(s)
    if s == 1
        @error "Lobatto nodes for one stages not defined."
    end

    D(k) = Polynomials.derivative(Polynomial(BigFloat[0, 1, -1])^(k-1), k-2)
    c = sort(real.(roots(D(s))))
    c[begin] = 0; c[end] = 1; c
end

get_lobatto_nodes (generic function with 1 method)

In [83]:
for s in 2:10
    @test Float64.(get_lobatto_nodes_legacy(s)) ≈ Float64.(get_lobatto_nodes(s))
end

In [84]:
get_lobatto_nodes(2)

2-element Array{BigFloat,1}:
 0.0
 1.0

In [85]:
get_lobatto_nodes(3)

3-element Array{BigFloat,1}:
 0.0
 0.50
 1.0

In [86]:
get_lobatto_nodes(4)

4-element Array{BigFloat,1}:
 0.0
 0.2763932022500210303590826331268723764559381640388474275729102754589479074362396
 0.723606797749978969640917366873127623544061835961152572427089724541052092563782
 1.0

In [87]:
get_lobatto_nodes(5)

5-element Array{BigFloat,1}:
 0.0
 0.1726731646460114281008537718765708222153959588022877212423398482923665410323274
 0.4999999999999999999999999999999999999999999999999999999999999999999999999998834
 0.8273268353539885718991462281234291777846040411977122787576601517076334589676855
 1.0

In [88]:
get_lobatto_nodes(6)

6-element Array{BigFloat,1}:
 0.0
 0.1174723380352676535744985130203309248171321557319478803362088220814723414805943
 0.35738424175967745184292450297956046404049826363678730409012479173615103454306
 0.6426157582403225481570754970204395359595017363632126959098752082638489654567069
 0.8825276619647323464255014869796690751828678442680521196637911779185276585199088
 1.0

In [89]:
get_lobatto_nodes(7)

7-element Array{BigFloat,1}:
 0.0
 0.08488805186071653506398389301626743020641481756400195420459339398355773991364278
 0.2655756032646428930981140590456168352972012641640776214486652703185222349413414
 0.5000000000000000000000000000000000000000000000000000000000000000000000000023749
 0.7344243967353571069018859409543831647027987358359223785513347296814777650474359
 0.9151119481392834649360161069837325697935851824359980457954066060164422601075838
 1.0

In [90]:
get_lobatto_nodes(8)

8-element Array{BigFloat,1}:
 0.0
 0.06412992574519669233127711938966828094810966516150832254029235721305050295352852
 0.2041499092834288489277446343010234050271495052413337516288702042649259099752277
 0.3953503910487605656156713698273243723522272974566594505545766538389345381780476
 0.6046496089512394343843286301726756276477727025433405494454233461610654618169866
 0.7958500907165711510722553656989765949728504947586662483711297957350740900454063
 0.9358700742548033076687228806103317190518903348384916774597076427869494970095886
 1.0

In [91]:
get_lobatto_nodes(9)

9-element Array{BigFloat,1}:
 0.0
 0.05012100229426992134382737779083102097425985221694778878534366575759336271684139
 0.1614068602446311232770572864543287746444851761930467102295183122514507360078053
 0.3184412680869109206446239656456703934896788611995609248398631346141947861835702
 0.4999999999999999999999999999999999999999999999999999999999999999999999999924261
 0.6815587319130890793553760343543296065103211388004390751601368653858052138495797
 0.8385931397553688767229427135456712253555148238069532897704816877485492639250917
 0.9498789977057300786561726222091689790257401477830522112146563342424066373564187
 1.0

In [92]:
get_lobatto_nodes(10)

10-element Array{BigFloat,1}:
 0.0
 0.04023304591677059308553366958883093292322846227686206425518692770786627926104315
 0.1306130674472474624984469125700846374919074493115366572674455034724233421300869
 0.2610375250947777521694124536343710010566135533347167655428715801541887244572744
 0.4173605211668064876868901170209132333844248282252581344335502139476058517342122
 0.5826394788331935123131098829790867666155751717747418655664497860523941485414154
 0.738962474905222247830587546365628998943386446665283234457128419845811274261537
 0.8693869325527525375015530874299153625080925506884633427325544965275766608982374
 0.9597669540832294069144663304111690670767715377231379357448130722921337165088503
 1.0

## Weights

In [93]:
function get_lobatto_weights_legacy(s)
    if s == 1
        @error "Lobatto weights for one stages not defined."
    elseif s == 2
        b = @dec128 [1/2, 1/2]
    elseif s == 3
        b = @dec128 [1/6,  2/3,  1/6]
    elseif s == 4
        b = @dec128 [1/12,   5/12,   5/12,   1/12]
    elseif s == 5
        b = @dec128 [1/20,   49/180,   16/45,   49/180,   1/20]
    else
        b = weights(LobattoLegendreQuadrature(s))
    end

    return b
end

get_lobatto_weights_legacy (generic function with 1 method)

In [97]:
function get_lobatto_weights(s)
    if s == 1
        @error "Lobatto weights for one stages not defined."
    end

    P(k,x) = Polynomials.derivative(Polynomial([-1, 0, 1])^k, k)(x) / factorial(k) / 2^k
    c = get_lobatto_nodes(s)
    b = [ 1 / ( s*(s-1) * P(s-1, 2c[i] - 1)^2 ) for i in 1:s ]
end

get_lobatto_weights (generic function with 1 method)

In [98]:
for s in 2:10
    @test Float64.(get_lobatto_weights_legacy(s)) ≈ Float64.(get_lobatto_weights(s))
end

In [99]:
get_lobatto_weights(2)

2-element Array{BigFloat,1}:
 0.50
 0.50

In [100]:
get_lobatto_weights(3)

3-element Array{BigFloat,1}:
 0.1666666666666666666666666666666666666666666666666666666666666666666666666666674
 0.6666666666666666666666666666666666666666666666666666666666666666666666666666695
 0.1666666666666666666666666666666666666666666666666666666666666666666666666666674

In [101]:
get_lobatto_weights(4)

4-element Array{BigFloat,1}:
 0.08333333333333333333333333333333333333333333333333333333333333333333333333333369
 0.4166666666666666666666666666666666666666666666666666666666666666666666666666652
 0.4166666666666666666666666666666666666666666666666666666666666666666666666666652
 0.08333333333333333333333333333333333333333333333333333333333333333333333333333369

In [102]:
get_lobatto_weights(5)

5-element Array{BigFloat,1}:
 0.05000000000000000000000000000000000000000000000000000000000000000000000000000011
 0.2722222222222222222222222222222222222222222222222222222222222222222222222222364
 0.3555555555555555555555555555555555555555555555555555555555555555555555555555539
 0.2722222222222222222222222222222222222222222222222222222222222222222222222222235
 0.05000000000000000000000000000000000000000000000000000000000000000000000000000011

In [103]:
get_lobatto_weights(6)

6-element Array{BigFloat,1}:
 0.03333333333333333333333333333333333333333333333333333333333333333333333333333359
 0.1892374781489234901583064041060123262381623469486258303271944256799821862795071
 0.2774291885177431765083602625606543404285043197180408363394722409866844803871771
 0.2774291885177431765083602625606543404285043197180408363394722409866844803871771
 0.1892374781489234901583064041060123262381623469486258303271944256799821862794942
 0.03333333333333333333333333333333333333333333333333333333333333333333333333333359

In [104]:
get_lobatto_weights(7)

7-element Array{BigFloat,1}:
 0.02380952380952380952380952380952380952380952380952380952380952380952380952380947
 0.1384130236807829740053502031450331467488136400899412345912671194817223119378067
 0.2158726906049313117089355111406811389654720741957730511230185948039919737765138
 0.2438095238095238095238095238095238095238095238095238095238095238095238095238091
 0.2158726906049313117089355111406811389654720741957730511230185948039919737765095
 0.1384130236807829740053502031450331467488136400899412345912671194817223119377851
 0.02380952380952380952380952380952380952380952380952380952380952380952380952380947

In [105]:
get_lobatto_weights(8)

8-element Array{BigFloat,1}:
 0.0178571428571428571428571428571428571428571428571428571428571428571428571428571
 0.1053521135717530196914960328878781622276730830805238840416702908213176249782087
 0.1705613462417521823821203385538740858875554878027908047375010369442754416180841
 0.2062293973293519407835264857011048947419142862595424540779715293772640762608029
 0.2062293973293519407835264857011048947419142862595424540779715293772640762608029
 0.1705613462417521823821203385538740858875554878027908047375010369442754416181122
 0.105352113571753019691496032887878162227673083080523884041670290821317624978227
 0.0178571428571428571428571428571428571428571428571428571428571428571428571428571

In [106]:
get_lobatto_weights(9)

9-element Array{BigFloat,1}:
 0.01388888888888888888888888888888888888888888888888888888888888888888888888888886
 0.08274768078040276252316986001460415291955361461257967072311179727342770476087284
 0.1372693562500808676403528092896863629706256104932546432683968144564555261002949
 0.1732142554865231725575657660698591439737663531254582030152941093585521432884773
 0.1857596371882086167800453514739229024943310657596371882086167800453514739229014
 0.1732142554865231725575657660698591439737663531254582030152941093585521432884773
 0.1372693562500808676403528092896863629706256104932546432683968144564555261002345
 0.08274768078040276252316986001460415291955361461257967072311179727342770476097323
 0.01388888888888888888888888888888888888888888888888888888888888888888888888888886

In [107]:
get_lobatto_weights(10)

10-element Array{BigFloat,1}:
 0.01111111111111111111111111111111111111111111111111111111111111111111111111111106
 0.06665299542553505556311358537769644905481293749889870744394545177223272630306645
 0.1124446710315632260597289108655239213769564569808753205698293668550268429720931
 0.1460213418398418789377911286872219461037441948438537722956863552702313819943145
 0.1637698805919487283282552639584465723533752995652610885794277149913979376192512
 0.1637698805919487283282552639584465723533752995652610885794277149913979376192512
 0.1460213418398418789377911286872219461037441948438537722956863552702313819943145
 0.1124446710315632260597289108655239213769564569808753205698293668550268429721601
 0.06665299542553505556311358537769644905481293749889870744394545177223272630305782
 0.01111111111111111111111111111111111111111111111111111111111111111111111111111106

## Coefficients

In [108]:
function get_lobatto_coefficients_a(s)
    c = get_lobatto_nodes(s)
    M = [ c[j]^(k-1) for k in 1:s, j in 1:s ]
    
    row(i) = begin
        r = [ c[i]^k / k for k in 1:s ]
        M \ r
    end
    
    vcat([row(i)' for i in 1:s]...)
end

get_lobatto_coefficients_a (generic function with 1 method)

In [109]:
get_lobatto_coefficients_a(2)

2×2 Array{BigFloat,2}:
 0.0   0.0
 0.50  0.50

In [110]:
get_lobatto_coefficients_a(3)

3×3 Array{BigFloat,2}:
 0.0       0.0        0.0
 0.208333  0.333333  -0.0416667
 0.166667  0.666667   0.166667

In [111]:
get_lobatto_coefficients_a(4)

4×4 Array{BigFloat,2}:
 0.0        0.0        0.0        -0.0
 0.110301   0.189699  -0.0339074   0.0103006
 0.0730328  0.450574   0.226967   -0.0269672
 0.0833333  0.416667   0.416667    0.0833333

In [112]:
get_lobatto_coefficients_a(5)

5×5 Array{BigFloat,2}:
 0.0        0.0        0.0         0.0        -0.0
 0.0677284  0.119745  -0.0217357   0.0106358  -0.00370014
 0.040625   0.303184   0.177778   -0.030962    0.009375
 0.0537001  0.261586   0.377291    0.152477   -0.0177284
 0.050      0.272222   0.355556    0.272222    0.050

In [113]:
get_lobatto_coefficients_a(6)

6×6 Array{BigFloat,2}:
 0.0        0.0         0.0         0.0          0.0          0.0
 0.0456798  0.0818678  -0.0148746   0.00762768  -0.00447178   0.00164343
 0.0259084  0.213841    0.133961   -0.0240041    0.0118077   -0.00412931
 0.0374626  0.17743     0.301433    0.143468    -0.0246033    0.00742495
 0.0316899  0.193709    0.269802    0.292304     0.10737     -0.0123465
 0.0333333  0.189237    0.277429    0.277429     0.189237     0.0333333

In [114]:
get_lobatto_coefficients_a(7)

7×7 Array{BigFloat,2}:
 0.0        0.0         0.0         0.0         …  -0.0         -0.0
 0.0328463  0.0593229  -0.0107686   0.00559759      0.0022171   -0.00083827
 0.0180022  0.157701    0.102355   -0.0184783      -0.00568186   0.00209998
 0.0275298  0.127788    0.237486    0.121905        0.0106248   -0.00372024
 0.0217095  0.144095    0.206295    0.262288       -0.0192881    0.0058073
 0.0246478  0.136196    0.219362    0.238212    …   0.0790901   -0.00903674
 0.0238095  0.138413    0.215873    0.24381         0.138413     0.0238095

In [115]:
get_lobatto_coefficients_a(8)

8×8 Array{BigFloat,2}:
 0.0        0.0         0.0          0.0         …   0.0         -0.0
 0.0247375  0.0448927  -0.00814077   0.00425408     -0.00122622   0.000471473
 0.0132587  0.12065     0.0799976   -0.0144808       0.00310495  -0.00117958
 0.0210344  0.0962802   0.189042     0.101246       -0.00560886   0.00207742
 0.0157797  0.110961    0.161144     0.224367        0.00907194  -0.00317721
 0.0190367  0.102247    0.175394     0.198597    …  -0.0152976    0.00459842
 0.0173857  0.106578    0.168716     0.208934        0.0604595   -0.00688037
 0.0178571  0.105352    0.170561     0.206229        0.105352     0.0178571

In [116]:
get_lobatto_coefficients_a(9)

9×9 Array{BigFloat,2}:
 0.0        0.0         0.0         0.0         …  -0.0           0.0
 0.0192938  0.0351255  -0.0063641   0.00333378      0.000733773  -0.000285196
 0.0101841  0.0950865   0.063932   -0.0115857      -0.00184751    0.000713077
 0.0165694  0.0750935   0.152882    0.0840855       0.00328962   -0.00125239
 0.01199    0.0878698   0.128682    0.189758       -0.00512215    0.00189887
 0.0151413  0.0794581   0.142366    0.165214    …   0.00765416   -0.00268048
 0.0131758  0.0845952   0.134514    0.177195       -0.0123388     0.00370481
 0.0141741  0.0820139   0.138343    0.17172         0.0476222    -0.00540495
 0.0138889  0.0827477   0.137269    0.173214        0.0827477     0.0138889

In [117]:
get_lobatto_coefficients_a(10)

10×10 Array{BigFloat,2}:
 0.0         0.0         0.0         …  -0.0          -0.0
 0.0154651   0.028218   -0.00510908     -0.000466142   0.00018252
 0.00807456  0.0767745   0.052118        0.00117017   -0.000456198
 0.013376    0.0601845   0.125653       -0.00206901    0.000800076
 0.00942487  0.0711997   0.104826        0.00316944   -0.0012079
 0.012319    0.0634836   0.117344    …  -0.00454672    0.00168624
 0.010311    0.068722    0.109372        0.00646845   -0.00226491
 0.0115673   0.0654828   0.114145       -0.0101215     0.00303655
 0.0109286   0.0671191   0.111775        0.038435     -0.00435404
 0.0111111   0.066653    0.112445        0.066653      0.0111111

In [118]:
function get_lobatto_coefficients_b(s)
    if s == 1
        @error "Lobatto IIIB coefficients for one stage are not defined."
    end

    b = get_lobatto_weights(s)
    c = get_lobatto_nodes(s)
    
    M = [ b[i] * c[i]^(k-1) for k in 1:s, i in 1:s ]
    
    column(j) = begin
        r = [ b[j] / k * (1 - c[j]^k) for k in 1:s ]
        M \ r
    end
    
    hcat([column(j) for j in 1:s]...)
end

get_lobatto_coefficients_b (generic function with 1 method)

In [119]:
get_lobatto_coefficients_b(2)

2×2 Array{BigFloat,2}:
 0.50  0.0
 0.50  0.0

In [120]:
get_lobatto_coefficients_b(3)

3×3 Array{BigFloat,2}:
 0.166667  -0.166667  0.0
 0.166667   0.333333  0.0
 0.166667   0.833333  0.0

In [121]:
get_lobatto_coefficients_b(4)

4×4 Array{BigFloat,2}:
 0.0833333  -0.134836   0.0515028  0.0
 0.0833333   0.226967  -0.0339074  0.0
 0.0833333   0.450574   0.189699   0.0
 0.0833333   0.365164   0.551503   0.0

In [122]:
get_lobatto_coefficients_b(5)

5×5 Array{BigFloat,2}:
 0.050  -0.0965215   0.0666667  -0.0201452   0.0
 0.050   0.152477   -0.0404401   0.0106358   0.0
 0.050   0.288864    0.177778   -0.0166414   0.0
 0.050   0.261586    0.395996    0.119745    0.0
 0.050   0.292367    0.288889    0.368744   -0.0

In [123]:
get_lobatto_coefficients_b(6)

6×6 Array{BigFloat,2}:
 0.0333333  -0.0700925   0.0617969  -0.0343677   0.00932993  0.0
 0.0333333   0.10737    -0.0360694   0.0173105  -0.00447178  0.0
 0.0333333   0.199384    0.143468   -0.0240041   0.00520292  0.0
 0.0333333   0.184035    0.301433    0.133961   -0.0101461   0.0
 0.0333333   0.193709    0.260119    0.313499    0.0818678   0.0
 0.0333333   0.179908    0.311797    0.215632    0.25933     0.0

In [124]:
get_lobatto_coefficients_b(7)

7×7 Array{BigFloat,2}:
 0.0238095  -0.0525337   0.0526528  …   0.0190398   -0.00487316   0.0
 0.0238095   0.0790901  -0.0300823     -0.00886159   0.0022171    0.0
 0.0238095   0.145318    0.113518       0.00957758  -0.00223703   0.0
 0.0238095   0.135235    0.232234      -0.0163609    0.00317781   0.0
 0.0238095   0.14065     0.206295       0.102355    -0.0069046    0.0
 0.0238095   0.136196    0.224734   …   0.245955     0.0593229   -0.0
 0.0238095   0.143286    0.196833       0.16322      0.190947    -0.0

In [125]:
get_lobatto_coefficients_b(8)

8×8 Array{BigFloat,2}:
 0.0178571  -0.0405923   0.0439215  …  -0.0112667    0.00278156   0.0
 0.0178571   0.0604595  -0.0247663      0.0050268   -0.00122622   0.0
 0.0178571   0.11038     0.0905637     -0.00483267   0.00113986   0.0
 0.0178571   0.103179    0.182538       0.00631198  -0.00138144   0.0
 0.0178571   0.106734    0.164249      -0.0119763    0.00217319   0.0
 0.0178571   0.104212    0.175394   …   0.0799976   -0.00502838   0.0
 0.0178571   0.106578    0.165535       0.195328     0.0448927    0.0
 0.0178571   0.102571    0.181828       0.12664      0.145944    -0.0

In [126]:
get_lobatto_coefficients_b(9)

9×9 Array{BigFloat,2}:
 0.0138889  -0.0322018   0.0366161  …   0.00704762  -0.00169915    0.0
 0.0138889   0.0476222  -0.0204688     -0.00306481   0.000733773   0.0
 0.0138889   0.086584    0.0733374      0.00275532  -0.000647457   0.0
 0.0138889   0.0811551   0.146451      -0.00315474   0.000713855   0.0
 0.0138889   0.0836996   0.132725       0.00454457  -0.000951871   0.0
 0.0138889   0.0820338   0.140424   …  -0.0091815    0.00159261    0.0
 0.0138889   0.0833951   0.134514       0.063932    -0.00383636    0.0
 0.0138889   0.0820139   0.140334       0.157738     0.0351255    -0.0
 0.0138889   0.0844468   0.130222       0.100653     0.114949      0.0

In [127]:
get_lobatto_coefficients_b(10)

10×10 Array{BigFloat,2}:
 0.0111111  -0.0261189   0.0307299  …  -0.00461673   0.00109489    0.0
 0.0111111   0.038435   -0.0170752      0.0019741   -0.000466142   0.0
 0.0111111   0.0696815   0.0603266     -0.00170044   0.000397009   0.0
 0.0111111   0.0654298   0.119721       0.00180066  -0.000411458   0.0
 0.0111111   0.0673549   0.108988      -0.00225923   0.0004962     0.0
 0.0111111   0.0661568   0.114704   …   0.00345651  -0.000701908   0.0
 0.0111111   0.0670645   0.110644      -0.00727681   0.00122318    0.0
 0.0111111   0.066256    0.114145       0.052118    -0.00302847   -0.0
 0.0111111   0.0671191   0.110471       0.12952      0.028218     -0.0
 0.0111111   0.0655581   0.117061       0.0817148    0.0927719    -0.0

### Lobatto-IIIC

In [128]:
s = 2
b = get_lobatto_weights(s)
c = get_lobatto_nodes(s)
M = [ c[j]^(k-1) for k in 1:s-1, j in 2:s ]

1×1 Array{BigFloat,2}:
 1.0

In [129]:
i = 1
r = [ c[i]^k / k - c[1]^(k-1) * b[1] for k in 1:s-1 ]

1-element Array{BigFloat,1}:
 -0.50

In [130]:
M \ r

1-element Array{BigFloat,1}:
 -0.50

In [131]:
i = 2
r = [ c[i]^k / k - c[1]^(k-1) * b[1] for k in 1:s-1 ]

1-element Array{BigFloat,1}:
 0.50

In [132]:
M \ r

1-element Array{BigFloat,1}:
 0.50

In [133]:
function get_lobatto_coefficients_c(s)
    if s == 1
        @error "Lobatto IIIC coefficients for one stage are not defined."
    end

    b = get_lobatto_weights(s)
    c = get_lobatto_nodes(s)
    M = [ c[j]^(k-1) for k in 1:s-1, j in 2:s ]
    
    row(i) = begin
        r = [ c[i]^k / k - c[1]^(k-1) * b[1] for k in 1:s-1 ]
        M \ r
    end
    
    hcat(b[1] * ones(s), vcat([row(i)' for i in 1:s]...))
end

get_lobatto_coefficients_c (generic function with 1 method)

In [134]:
get_lobatto_coefficients_c(2)

2×2 Array{BigFloat,2}:
 0.50  -0.50
 0.50   0.50

In [135]:
get_lobatto_coefficients_c(3)

3×3 Array{BigFloat,2}:
 0.166667  -0.333333   0.166667
 0.166667   0.416667  -0.0833333
 0.166667   0.666667   0.166667

In [136]:
get_lobatto_coefficients_c(4)

4×4 Array{BigFloat,2}:
 0.0833333  -0.186339   0.186339   -0.0833333
 0.0833333   0.25      -0.0942079   0.0372678
 0.0833333   0.427541   0.25       -0.0372678
 0.0833333   0.416667   0.416667    0.0833333

In [137]:
get_lobatto_coefficients_c(5)

5×5 Array{BigFloat,2}:
 0.050  -0.116667   0.133333   -0.116667    0.050
 0.050   0.161111  -0.0690115   0.0520022  -0.0214286
 0.050   0.281309   0.202778   -0.052837    0.01875
 0.050   0.27022    0.367424    0.161111   -0.0214286
 0.050   0.272222   0.355556    0.272222    0.050

In [138]:
get_lobatto_coefficients_c(6)

6×6 Array{BigFloat,2}:
 0.0333333  -0.0794224   0.0961646  -0.0961646   0.0794224  -0.0333333
 0.0333333   0.111285   -0.0504934   0.0432465  -0.0338894   0.0139899
 0.0333333   0.19615     0.155381   -0.0454246   0.0294989  -0.0115543
 0.0333333   0.187269    0.28952     0.155381   -0.0344421   0.0115543
 0.0333333   0.189794    0.274543    0.287563    0.111285   -0.0139899
 0.0333333   0.189237    0.277429    0.277429    0.189237    0.0333333

In [139]:
get_lobatto_coefficients_c(7)

7×7 Array{BigFloat,2}:
 0.0238095  -0.0574069   0.0716926  …   0.0716926  -0.0574069   0.0238095
 0.0238095   0.0811113  -0.037979      -0.0306994   0.0240055  -0.00987501
 0.0238095   0.143699    0.119841       0.0270639  -0.0196838   0.00790728
 0.0238095   0.136758    0.226284      -0.0328149   0.0195946  -0.00744048
 0.0238095   0.139032    0.212618       0.119841   -0.0243513   0.00790728
 0.0238095   0.138217    0.216838   …   0.224117    0.0811113  -0.00987501
 0.0238095   0.138413    0.215873       0.215873    0.138413    0.0238095

In [140]:
function get_lobatto_coefficients_c̄(s)
    if s == 1
        @error "Lobatto IIIC coefficients for one stage are not defined."
    end

    b = get_lobatto_weights(s)
    c = get_lobatto_nodes(s)
    M = [ c[j]^(k-1) for k in 1:s-1, j in 1:s-1 ]
    
    row(i) = begin
        r = [ c[i]^k / k for k in 1:s-1 ]
        M \ r
    end
    
    hcat(vcat([row(i)' for i in 1:s]...), zeros(s))
end

get_lobatto_coefficients_c̄ (generic function with 1 method)

In [141]:
get_lobatto_coefficients_c̄(2)

2×2 Array{BigFloat,2}:
 0.0  0.0
 1.0  0.0

In [142]:
get_lobatto_coefficients_c̄(3)

3×3 Array{BigFloat,2}:
 0.0   0.0   0.0
 0.25  0.25  0.0
 0.0   1.0   0.0

In [143]:
get_lobatto_coefficients_c̄(4)

4×4 Array{BigFloat,2}:
 0.0        0.0        0.0        0.0
 0.120601   0.166667  -0.0108746  0.0
 0.0460655  0.510875   0.166667   0.0
 0.166667   0.230328   0.603006   0.0

In [144]:
get_lobatto_coefficients_c̄(5)

5×5 Array{BigFloat,2}:
 0.0          0.0        0.0         0.0         0.0
 0.0714286    0.111111  -0.0118687   0.00200217  0.0
 0.03125      0.325059   0.152778   -0.00908696  0.0
 0.0714286    0.22022    0.424567    0.111111    0.0
 1.03634e-76  0.388889   0.222222    0.388889    0.0

### Lobatto-IIIF

In [145]:
function get_lobatto_coefficients_f(s)
    c = get_lobatto_nodes(s)
    M = [ 1 / (k + j - 1) for k in big.(1:s), j in big.(1:s) ]
    r = [ 1 / s / (s + k) for k in big.(1:s) ]
    α = M \ r
    
    Vₛ = [ c[i]^(j-1) for i in big.(1:s), j in big.(1:s) ]
    Aₛ = zeros(BigFloat, s, s)
    for i in big.(2:s)
       Aₛ[i,i-1] = 1 / (i-1)
    end
    Aₛ[:,s] = α
    
    Vₛ * Aₛ * inv(Vₛ)
end

get_lobatto_coefficients_f (generic function with 1 method)

In [146]:
get_lobatto_coefficients_f(2)

2×2 Array{BigFloat,2}:
 0.0833333  -0.0833333
 0.583333    0.416667

In [147]:
get_lobatto_coefficients_f(3)

3×3 Array{BigFloat,2}:
 0.0333333  -0.0666667   0.0333333
 0.208333    0.333333   -0.0416667
 0.133333    0.733333    0.133333

In [148]:
get_lobatto_coefficients_f(4)

4×4 Array{BigFloat,2}:
 0.0178571  -0.0399298   0.0399298  -0.0178571
 0.106729    0.197685   -0.0418933   0.013872
 0.0694613   0.45856     0.218981   -0.0233958
 0.10119     0.376737    0.456596    0.0654762

In [149]:
get_lobatto_coefficients_f(5)

5×5 Array{BigFloat,2}:
 0.0111111  -0.0259259   0.0296296  -0.0259259   0.0111111
 0.064611    0.127019   -0.0300488   0.0179098  -0.00681754
 0.040625    0.303184    0.177778   -0.030962    0.009375
 0.0568175   0.254312    0.385604    0.145204   -0.014611
 0.0388889   0.298148    0.325926    0.298148    0.0388889

In [150]:
get_lobatto_coefficients_f(6)

6×6 Array{BigFloat,2}:
 0.00757576  -0.0180505   0.0218556  -0.0218556   0.0180505  -0.00757576
 0.0432473    0.0876637  -0.0218923   0.0146453  -0.0102677   0.00407594
 0.0266574    0.212056    0.136122   -0.0261649   0.0135923  -0.00487832
 0.0382117    0.175645    0.303594    0.141308   -0.0228187   0.00667594
 0.0292574    0.199505    0.262784    0.299321    0.101574   -0.00991396
 0.0409091    0.171187    0.299285    0.255574    0.207288    0.0257576

### Projective coefficients

In [151]:
function get_glrk_nodes(s)
    if s == 1
        c = Vector([1//2])
    elseif s == 2
        c = [1/2-√3/6, 1/2+√3/6]
    elseif s == 3
        c = [1/2-√15/10,  1/2,        1/2+√15/10 ]
    elseif s == 4
        c = [
          1/2-√(3/7+2*√30/35)/2,
          1/2-√(3/7-2*√30/35)/2,
          1/2+√(3/7-2*√30/35)/2,
          1/2+√(3/7+2*√30/35)/2
        ]
    else
        @error "GLRK nodes for " * string(s) * " stages not implemented."
    end

    return big.(c)
end


get_glrk_nodes (generic function with 1 method)

In [163]:
function get_lobatto_coefficients_glrk(s, σ=s+1)
    if σ == 1
        @error "Lobatto IIIA coefficients for one stage are not defined."
    end

    c = get_glrk_nodes(s)
    c̄ = get_lobatto_nodes(σ)
    M = [ c[j]^(k-1) for k in 1:s, j in 1:s ]
    
    row(i) = begin
        r = [ c̄[i]^k / k for k in 1:s ]
        M \ r
    end
    
    vcat([row(i)' for i in 1:σ]...)
end

get_lobatto_coefficients_glrk (generic function with 2 methods)

In [164]:
get_lobatto_coefficients_glrk(1)

2×1 Array{BigFloat,2}:
 0.0
 1.0

In [165]:
get_lobatto_coefficients_glrk(2)

3×2 Array{BigFloat,2}:
 0.0       0.0
 0.466506  0.0334936
 0.50      0.50

In [166]:
[
                [0         0       ]
                [1/4+√3/8  1/4-√3/8]
                [1/2       1/2     ]
            ]

3×2 Array{Float64,2}:
 0.0       0.0
 0.466506  0.0334936
 0.5       0.5

In [167]:
get_lobatto_coefficients_glrk(3)

4×3 Array{BigFloat,2}:
 0.0       0.0         0.0
 0.255566  0.0234606  -0.00263316
 0.280411  0.420984    0.022212
 0.277778  0.444444    0.277778

In [168]:
[
                [0                     0              0                 ]
                [5/36-√5/180+√15/30    2/9-4*√5/45    5/36-√15/30-√5/180]
                [5/36+√5/180+√15/30    2/9+4*√5/45    5/36+√5/180-√15/30]
                [5/18                  4/9            5/18              ]
            ]

4×3 Array{Float64,2}:
 0.0       0.0         0.0
 0.255566  0.0234606  -0.00263316
 0.280411  0.420984    0.022212
 0.277778  0.444444    0.277778

In [169]:
get_lobatto_coefficients_glrk(4)

5×4 Array{BigFloat,2}:
 0.0       0.0         0.0         -0.0
 0.159167  0.0156555  -0.00264993   0.000500452
 0.176106  0.304916    0.0211566   -0.00217852
 0.173427  0.328723    0.310417     0.0147603
 0.173927  0.326073    0.326073     0.173927

In [170]:
get_lobatto_coefficients_glrk(1,2)

2×1 Array{BigFloat,2}:
 0.0
 1.0

In [171]:
get_lobatto_coefficients_glrk(2,2)

2×2 Array{BigFloat,2}:
 0.0   0.0
 0.50  0.50

In [172]:
get_lobatto_coefficients_glrk(3,2)

2×3 Array{BigFloat,2}:
 0.0       0.0       0.0
 0.277778  0.444444  0.277778

In [175]:
Float64[ 0      0      0
               5//18  8//18  5//18 ]

2×3 Array{Float64,2}:
 0.0       0.0       0.0
 0.277778  0.444444  0.277778

In [173]:
get_lobatto_coefficients_glrk(4,2)

2×4 Array{BigFloat,2}:
 0.0       0.0       0.0       -0.0
 0.173927  0.326073  0.326073   0.173927

In [176]:
Float64[ 0            0            0            0
               1//4-√30/72  1//4+√30/72  1//4+√30/72  1//4-√30/72 ]

2×4 Array{Float64,2}:
 0.0       0.0       0.0       0.0
 0.173927  0.326073  0.326073  0.173927

### D Vectors

In [178]:
function get_lobatto_d_vector(s)
    q = (get_lobatto_nodes(s))
    l = LagrangeBasis(q)
    v = [deriv_basis(l, j, i) for i in 1:s, j in 1:s]
    nullspace(v')
end

get_lobatto_d_vector (generic function with 1 method)

In [181]:
get_lobatto_d_vector(2)

2×1 Array{BigFloat,2}:
 -0.7071067811865475244008443621048490392848359376884740365883398689953662392310596
  0.707106781186547524400844362104849039284835937688474036588339868995366239231051

In [182]:
get_lobatto_d_vector(3)

3×1 Array{BigFloat,2}:
  0.4082482904638630163662140124509818986609912467761116880721154278751600629095585
 -0.8164965809277260327324280249019637973219824935522233761442308557503201258191083
  0.4082482904638630163662140124509818986609912467761116880721154278751600629095455

In [183]:
get_lobatto_d_vector(4)

4×1 Array{BigFloat,2}:
 -0.2886751345948128822545743902509787278238008756350634380093011632419888361514404
  0.6454972243679028141965442332970666018054869508819318044312622943522471819894532
 -0.6454972243679028141965442332970666018054869508819318044312622943522471819895568
  0.2886751345948128822545743902509787278238008756350634380093011632419888361514663

In [184]:
get_lobatto_d_vector(5)

5×1 Array{BigFloat,2}:
  0.2236067977499789696409173668731276235440618359611525724270897245410520925637841
 -0.5217491947499509291621405227039644549361442839093560023298760239291215493156611
  0.5962847939999439190424463116616736627841648958964068598055725987761389135034387
 -0.5217491947499509291621405227039644549361442839093560023298760239291215493152983
  0.2236067977499789696409173668731276235440618359611525724270897245410520925637021

In [185]:
get_lobatto_d_vector(6)

6×1 Array{BigFloat,2}:
 -0.1825741858350553711523232609336007113175815649993277514089648165774977590409217
  0.4350143424634680825574984612306048024944868112531292454751727225037742358223348
 -0.5267154720698293446974006159247453707907168288072631317899442309615687299173712
  0.5267154720698293446974006159247453707907168288072631317899442309615687299164212
 -0.435014342463468082557498461230604802494486811253129245475172722503774235821998
  0.1825741858350553711523232609336007113175815649993277514089648165774977590416213

In [186]:
get_lobatto_d_vector(7)

7×1 Array{BigFloat,2}:
 -0.1543033499620919102610944627639999204215524835013892035645560570907051756661838
  0.3720390082784102009107576740633937685699419395989193388362289544129978336055676
 -0.4646210182556653470674143517217937208228734296997528609749625886674209390025942
  0.4937707198786941128355022808447997453489679472044454514065793826902565621358343
 -0.4646210182556653470674143517217937208228734296997528609749625886674209389614688
  0.3720390082784102009107576740633937685699419395989193388362289544129978335897979
 -0.1543033499620919102610944627639999204215524835013892035645560570907051757009379

In [187]:
get_lobatto_d_vector(8)

8×1 Array{BigFloat,2}:
  0.1336306209562121923422767404398767607770007074206688195108480524042869698625358
 -0.3245799032160694629402394332353267422766759439107469584031812889157527384447819
  0.412990733844903816120563993452587074868384688462735438186876302814099636636809
 -0.4541248697542911938770867892511123011357377369036088004283434165119070152415105
  0.454124869754291193877086789251112301135737736903608800428343416511907015224683
 -0.4129907338449038161205639934525870748683846884627354381868763028140996367233477
  0.3245799032160694629402394332353267422766759439107469584031812889157527384801772
 -0.1336306209562121923422767404398767607770007074206688195108480524042869697946123

In [188]:
get_lobatto_d_vector(9)

9×1 Array{BigFloat,2}:
 -0.1178511301977579207334740603508081732141393229480790060980566448325610398811246
  0.2876589661046614457207911986206576829212644508945925909031668161762514712826078
 -0.3704987938577949913922399229409546274538331855890691637572840930275627510162984
  0.4161901674553630928889896378840114916239913910333286186743346436634125068264729
 -0.4309984190089432529681337064258127477545666667815460794443214439590803743752917
  0.4161901674553630928889896378840114916239913910333286186743346436634125068885281
 -0.3704987938577949913922399229409546274538331855890691637572840930275627508554065
  0.2876589661046614457207911986206576829212644508945925909031668161762514711490451
 -0.1178511301977579207334740603508081732141393229480790060980566448325610400184732